const TREE_THRESHOLDS = [1, 2, 4, 7, 11, 18, 30, 50];
const TREE_CROWN_THRESHOLD = 60;
const TREE_LABEL_STEP = 7;
const STREAK_WEEK_DAYS = 7;

const CO2_PER_TREE_KG = 21;
const CO2_PER_CAR_MILE_KG = 0.404;
const CO2_PER_LITER_WATER_KG = 0.001;
const CO2_PER_KWH_KG = 0.4;

const MAX_RECENT_SCANS = 10;

const WEATHER_CACHE_MS = 15 * 60 * 1000;
const AQI_CACHE_MS = 30 * 60 * 1000;
const CLIMATE_CACHE_MS = 24 * 60 * 60 * 1000;
const COUNTRY_CACHE_MS = 60 * 60 * 1000;

const CO2_VALIDATION_MIN = 0.01;
const CO2_VALIDATION_MAX = 100;

export {
  TREE_THRESHOLDS,
  TREE_CROWN_THRESHOLD,
  TREE_LABEL_STEP,
  STREAK_WEEK_DAYS,
  CO2_PER_TREE_KG,
  CO2_PER_CAR_MILE_KG,
  CO2_PER_LITER_WATER_KG,
  CO2_PER_KWH_KG,
  MAX_RECENT_SCANS,
  WEATHER_CACHE_MS,
  AQI_CACHE_MS,
  CLIMATE_CACHE_MS,
  COUNTRY_CACHE_MS,
  CO2_VALIDATION_MIN,
  CO2_VALIDATION_MAX,
};